//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Comment1 { get; set; }
        public int AuthorId { get; set; }
        public int BlogId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Blog Blog { get; set; }
    }
}
